### PR TITLE
Fixed a few incorrect statements.

### PR DESCRIPTION
**Pull request by nkgupta1**

### CODE REVIEW

**Comment by AGFeldman** [comment]
Hmm, I merged a conflicting pull request about a minute ago :/  https://github.com/caltechcs2/dna_carving/pull/2

**Comment by nkgupta1** [comment]
Different ways of fixing the same mistake.

**Comment by AGFeldman** [comment]
Yup. Could you just remove that part from your pull request? As is, it isn't possible to automatically merge.

**Comment by AGFeldman** [comment]
Thanks!

**Pull request merged**
